name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          REPO_DIR="/root/projects/backend/hrm_backend"
          REPO_URL="git@github.com:naseerai/hrm_backend.git"

          echo "Checking if repo exists..."

          if [ ! -d "$REPO_DIR/.git" ]; then
            echo "Repository not found. Cloning..."
            mkdir -p /root/projects/backend
            cd /root/projects/backend
            git clone $REPO_URL
          else
            echo "Repository exists. Pulling latest code..."
            cd $REPO_DIR
            git pull origin main
          fi

          echo "Navigating to repo..."
          cd $REPO_DIR

          echo "Stopping and removing old containers..."
          docker compose down || true

          echo "Removing old Docker images..."
          docker images | grep "hrm_backend" | awk '{print $3}' | xargs -r docker rmi -f || true

          echo "Copying .env.local to .env..."
          cp .env.local .env

          echo "Rebuilding image..."
          docker compose build --no-cache

          echo "Starting new container..."
          docker compose up -d

          echo "Deployment Successful!"
